# Base image for development
FROM node:20 AS development

# Set working directory
WORKDIR /frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Expose React's default port
EXPOSE 3000

# Run React's development server
CMD ["npm", "run", "dev"]
