export const ROUTES = {
  LOGIN: "/login",
  FORGOT_PASSWORD: "/auth/forgot-password",
  LANDING_PAGE: "/",
  PORTAL: "/portal",
  DASHBOARD: "/portal/dashboard",
  FRONT_DESK: "/portal/front-desk",
  RATES: "/portal/rate",
  BOOKINGS_AND_CHECKINS: "/portal/reservations",
  CITY_TAX: "/portal/city-tax",
  ISTAT: "/portal/istat",
  INVOICING : "/portal/invoicing",
  PROPERTY_TYPES: "/portal/properties/property-types",
  STRUCTURES: "/portal/properties/structures",
  PROPERTY_TYPES_BY_STRUCTURE__ID:
    "/portal/properties/structures/:structureId/property-types",
  USER_MANAGEMENT: "/portal/global-user-management",
  STRUCTURE_USERS: "/portal/properties/structure-users",
  STRUCUTURE_USERS_BY_STRUCUTRE_ID:
    "/portal/properties/structures/:structureId/structure-users",
  PROPERTIES: "/portal/properties/rooms",
  PORTALS: "/portal/configuration/portals",
  BOOKING_DETAILS: "/portal/bookings/booking-details/:id",
  ACCEPT_INVITATION: "/accept-invitation/:invitation_id",
  BUREAUCRACY: "/portal/configuration/bureaucracy",
  PROFILE: "/portal/my-profile/my-account",
  GUEST_CONFIGURATION: "/portal/guest-configuration",
  SIGNUP: "/signup",
  PUBLIC_CHECKIN_PAGE:"/checkin/:bookingUid",
} as const;
